name: codefire
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  bonfire: ^2.10.10
  flutter_highlight: ^0.7.0
  # dart_eval: ^0.5.4
  flutter_riverpod: ^2.0.2
  code_text_field: ^1.0.2
  flutter_js: ^0.5.0+6
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: NotoSansMono
      fonts:
        - asset: assets/fonts/NotoSansMono-Regular.ttf